### ISSUE TITLE
The generated PDF, code block will not be rendered

### ISSUE THREAD

**Issue by fatherxtreme123** [Bklieger/groqbook#14]
The generated PDF, code block will not be rendered
![image](https://github.com/Bklieger/groqbook/assets/143677684/41321e2a-88fd-412a-aa78-07cbbf069cc5)

**Comment by Bklieger** [comment]
<img width="729" alt="Screenshot 2024-06-25 at 11 47 40 AM" src="https://github.com/Bklieger/groqbook/assets/62450410/7d7157eb-bd46-4ab2-bf59-dfd258c4974d">

Fixed with new commit. PDFs are now styled and show code blocks.
