### ISSUE TITLE
After downloading the book, the beginning will say "Here is the generated chapter"

### ISSUE THREAD

**Issue by fatherxtreme123** [Bklieger/groqbook#25]
![image](https://github.com/Bklieger/groqbook/assets/143677684/76ac8a69-8680-442f-b3ae-4309b54e7f01)
After downloading the book, the beginning will say "Here is the generated chapter"

**Comment by Bklieger** [comment]
How often is this issue occurring? If you find it happens often with a particular prompt, please provide such prompt for reproducing the issue.

It is an expected behavior that there will be occasional hallucinations due to the nature of LLMs.

**Comment by fatherxtreme123** [comment]
![image](https://github.com/Bklieger/groqbook/assets/143677684/16541631-2d19-46c9-9730-7492dae7e62c)
Appears 22 times when generating book once
The prompt I use:
“What Are LArge language model , LLMs”
I try to write other prompt "what is javascript"
![image](https://github.com/Bklieger/groqbook/assets/143677684/d050fa87-7c63-42ef-9a9c-1441c34b367e)
will still appear

**Comment by Bklieger** [comment]
Thank you, investigating now.

**Comment by Bklieger** [comment]
This issue should be fixed now through the latest push which improved the prompting. See attached test cases based on the two that were provided. Please re-open the issue if you find the issue occurring again.

<img width="832" alt="Screenshot 2024-07-04 at 8 03 11 PM" src="https://github.com/Bklieger/groqbook/assets/62450410/9d514af5-922c-4d42-8fff-4940ca07e28e">
<img width="797" alt="Screenshot 2024-07-04 at 8 03 22 PM" src="https://github.com/Bklieger/groqbook/assets/62450410/171c31ad-c9a6-48a9-bb38-acaafc5f716d">
<img width="812" alt="Screenshot 2024-07-04 at 8 03 54 PM" src="https://github.com/Bklieger/groqbook/assets/62450410/498f3013-2f75-4156-a551-3125b2ad8fcb">
<img width="811" alt="Screenshot 2024-07-04 at 8 04 01 PM" src="https://github.com/Bklieger/groqbook/assets/62450410/aa80cecf-1b64-4ac0-a894-05b0f9b58a0b">
